### ISSUE TITLE
Playback script not using bream4 config file?

### ISSUE THREAD

**Issue by JensUweUlrich** [alexomics/fillet#1]
I'm not sure if this is an issue caused by fillet or by the playback script. I could add a bulk fast5 file as simulation to custom_settings in sequencing_MIN106_DNA.toml of bream4/configuration. But when I execute the playback custom script from within MinKNOW, I get the following error messages in the log file:

_2019-10-23 14:39:54,788.788 [WARNING]: root We can no longer use the Bream-3 GUI to set the configuration, as Bream-3 has been retired.
2019-10-23 14:39:54,790.790 [ERROR]: root Error in playback script: 
Traceback (most recent call last):
  File "/opt/ONT/MinKNOW/python/recipes/playback.py", line 620, in <module>
    run(args)
  File "/opt/ONT/MinKNOW/python/recipes/playback.py", line 374, in run
    if not os.path.exists(user_config.path):
  File "/opt/ONT/MinKNOW/ont-python/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError:_ coercing to Unicode: need string or buffer, NoneType found_

It seems, that the config file, modified by fillet is not used. Is this an issue related to a wrong Bream version?

**Comment by alexomics** [comment]
Sorry that it's taken so long to get to this. The way that simulations work has changed quite drastically in the last few months. If you've added the `simulation` parameter in the custom settings and verified that it's there then you need to right click on the minion position that you want to run the simulation from and select *reload scripts* then start the run normally and you should be good to go.
